# Generated by Django 5.2.1 on 2025-06-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0003_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
    ]
