# Generated by Django 5.2.1 on 2025-06-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0004_remove_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default='Default description', max_length=250),
        ),
    ]
